//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCD2_mod_manager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCD2_mod_manager.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid file type in settings. Only .exe files are allowed. ähnelt.
        /// </summary>
        internal static string ErrorInvalidFileType {
            get {
                return ResourceManager.GetString("ErrorInvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The game was not found in the default path. Please select the game executable manually. ähnelt.
        /// </summary>
        internal static string ErrorGamePathRequired {
            get {
                return ResourceManager.GetString("ErrorGamePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The game path is required to continue. Exiting the application. ähnelt.
        /// </summary>
        internal static string ErrorGamePathRequiredExit {
            get {
                return ResourceManager.GetString("ErrorGamePathRequiredExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The saved game path is invalid. Please update the path in settings. ähnelt.
        /// </summary>
        internal static string ErrorInvalidPath {
            get {
                return ResourceManager.GetString("ErrorInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The game executable path is invalid. Please update the path in settings before starting the game. ähnelt.
        /// </summary>
        internal static string ErrorInvalidExecutable {
            get {
                return ResourceManager.GetString("ErrorInvalidExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only .exe files can be executed. ähnelt.
        /// </summary>
        internal static string ErrorSecurityBlocked {
            get {
                return ResourceManager.GetString("ErrorSecurityBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No mods selected to load. ähnelt.
        /// </summary>
        internal static string WarningNoModsSelected {
            get {
                return ResourceManager.GetString("WarningNoModsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorting is disabled during search. ähnelt.
        /// </summary>
        internal static string ErrorSortingDisabled {
            get {
                return ResourceManager.GetString("ErrorSortingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only change the mod order while sorting by load order. ähnelt.
        /// </summary>
        internal static string ErrorActionNotAllowed {
            get {
                return ResourceManager.GetString("ErrorActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No mod selected. ähnelt.
        /// </summary>
        internal static string ErrorNoModSelected {
            get {
                return ResourceManager.GetString("ErrorNoModSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod number is missing or invalid. ähnelt.
        /// </summary>
        internal static string ErrorModNumberMissing {
            get {
                return ResourceManager.GetString("ErrorModNumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The mod folder does not exist or is not specified. ähnelt.
        /// </summary>
        internal static string ErrorModFolderNotExists {
            get {
                return ResourceManager.GetString("ErrorModFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to delete mod: {0} ähnelt.
        /// </summary>
        internal static string ErrorFailedToDeleteMod {
            get {
                return ResourceManager.GetString("ErrorFailedToDeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to identify the mod to delete. ähnelt.
        /// </summary>
        internal static string ErrorFailedToIdentifyMod {
            get {
                return ResourceManager.GetString("ErrorFailedToIdentifyMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to start the game: {0} ähnelt.
        /// </summary>
        internal static string ErrorFailedToStartGame {
            get {
                return ResourceManager.GetString("ErrorFailedToStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added mod: {0} (Version: {1}) ähnelt.
        /// </summary>
        internal static string InfoModAdded {
            get {
                return ResourceManager.GetString("InfoModAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted mod: {0} ähnelt.
        /// </summary>
        internal static string InfoModDeleted {
            get {
                return ResourceManager.GetString("InfoModDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod order saved to {0}. ähnelt.
        /// </summary>
        internal static string InfoModOrderSaved {
            get {
                return ResourceManager.GetString("InfoModOrderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not logged in to Nexus Mods ähnelt.
        /// </summary>
        internal static string InfoNotLoggedIn {
            get {
                return ResourceManager.GetString("InfoNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logged in as {0} ähnelt.
        /// </summary>
        internal static string InfoLoggedInAs {
            get {
                return ResourceManager.GetString("InfoLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Mod Number: ähnelt.
        /// </summary>
        internal static string PromptEnterModNumber {
            get {
                return ResourceManager.GetString("PromptEnterModNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter mod name: ähnelt.
        /// </summary>
        internal static string PromptEnterModName {
            get {
                return ResourceManager.GetString("PromptEnterModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter note for mod: ähnelt.
        /// </summary>
        internal static string PromptEnterNote {
            get {
                return ResourceManager.GetString("PromptEnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod note: ähnelt.
        /// </summary>
        internal static string PromptModNote {
            get {
                return ResourceManager.GetString("PromptModNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new mod number: ähnelt.
        /// </summary>
        internal static string PromptChangeModNumber {
            get {
                return ResourceManager.GetString("PromptChangeModNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod Number ähnelt.
        /// </summary>
        internal static string TitleModNumber {
            get {
                return ResourceManager.GetString("TitleModNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Mod Name ähnelt.
        /// </summary>
        internal static string TitleChangeModName {
            get {
                return ResourceManager.GetString("TitleChangeModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Mod Note ähnelt.
        /// </summary>
        internal static string TitleChangeModNote {
            get {
                return ResourceManager.GetString("TitleChangeModNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Mod Number ähnelt.
        /// </summary>
        internal static string TitleChangeModNumber {
            get {
                return ResourceManager.GetString("TitleChangeModNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod note ähnelt.
        /// </summary>
        internal static string TitleModNote {
            get {
                return ResourceManager.GetString("TitleModNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error loading mods ähnelt.
        /// </summary>
        internal static string ErrorFailedToLoadMods {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing mod... ähnelt.
        /// </summary>
        internal static string StatusInstallingMod {
            get {
                return ResourceManager.GetString("StatusInstallingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added mod: {0} (Version: {1}) ähnelt.
        /// </summary>
        internal static string StatusModAdded {
            get {
                return ResourceManager.GetString("StatusModAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to install mod ähnelt.
        /// </summary>
        internal static string StatusModInstallFailed {
            get {
                return ResourceManager.GetString("StatusModInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted mod: {0} ähnelt.
        /// </summary>
        internal static string StatusModDeleted {
            get {
                return ResourceManager.GetString("StatusModDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing mod from folder... ähnelt.
        /// </summary>
        internal static string StatusInstallingModFromFolder {
            get {
                return ResourceManager.GetString("StatusInstallingModFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string DialogTitleWarning {
            get {
                return ResourceManager.GetString("DialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string DialogTitleInformation {
            get {
                return ResourceManager.GetString("DialogTitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security Error ähnelt.
        /// </summary>
        internal static string DialogTitleSecurityError {
            get {
                return ResourceManager.GetString("DialogTitleSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Path Required ähnelt.
        /// </summary>
        internal static string DialogTitleGamePathRequired {
            get {
                return ResourceManager.GetString("DialogTitleGamePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Path ähnelt.
        /// </summary>
        internal static string DialogTitleInvalidPath {
            get {
                return ResourceManager.GetString("DialogTitleInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security Blocked ähnelt.
        /// </summary>
        internal static string DialogTitleSecurityBlocked {
            get {
                return ResourceManager.GetString("DialogTitleSecurityBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language Changed ähnelt.
        /// </summary>
        internal static string DialogTitleLanguageChanged {
            get {
                return ResourceManager.GetString("DialogTitleLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language has been changed. The application needs to be restarted for the changes to take effect. Restart now? ähnelt.
        /// </summary>
        internal static string DialogMessageLanguageChanged {
            get {
                return ResourceManager.GetString("DialogMessageLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Backups set to {0}. ähnelt.
        /// </summary>
        internal static string InfoMaxBackupsSet {
            get {
                return ResourceManager.GetString("InfoMaxBackupsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid number. Please enter a positive integer. ähnelt.
        /// </summary>
        internal static string ErrorInvalidNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod endorsed successfully! ähnelt.
        /// </summary>
        internal static string InfoModEndorsed {
            get {
                return ResourceManager.GetString("InfoModEndorsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endorse failed ähnelt.
        /// </summary>
        internal static string ErrorEndorseFailed {
            get {
                return ResourceManager.GetString("ErrorEndorseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening folder: {0} ähnelt.
        /// </summary>
        internal static string ErrorOpeningFolder {
            get {
                return ResourceManager.GetString("ErrorOpeningFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        internal static string DialogTitleSuccess {
            get {
                return ResourceManager.GetString("DialogTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action Not Allowed ähnelt.
        /// </summary>
        internal static string DialogTitleActionNotAllowed {
            get {
                return ResourceManager.GetString("DialogTitleActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version ({0}) is available. Do you want to update? ähnelt.
        /// </summary>
        internal static string PromptNewVersionAvailable {
            get {
                return ResourceManager.GetString("PromptNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Available ähnelt.
        /// </summary>
        internal static string DialogTitleUpdateAvailable {
            get {
                return ResourceManager.GetString("DialogTitleUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game installation not found ähnelt.
        /// </summary>
        internal static string ErrorGameInstallationNotFound {
            get {
                return ResourceManager.GetString("ErrorGameInstallationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialization error: {0} ähnelt.
        /// </summary>
        internal static string ErrorInitialization {
            get {
                return ResourceManager.GetString("ErrorInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile '{0}' not found ähnelt.
        /// </summary>
        internal static string ErrorProfileNotFound {
            get {
                return ResourceManager.GetString("ErrorProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not detect game version ähnelt.
        /// </summary>
        internal static string ErrorGameVersion {
            get {
                return ResourceManager.GetString("ErrorGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closing this window will exit the application. Do you want to continue? ähnelt.
        /// </summary>
        internal static string ExitApplicationMessage {
            get {
                return ResourceManager.GetString("ExitApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No game was selected. The application will be closed. ähnelt.
        /// </summary>
        internal static string NoGameSelectedMessage {
            get {
                return ResourceManager.GetString("NoGameSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical error: No game could be selected. ähnelt.
        /// </summary>
        internal static string ErrorNoGameSelected {
            get {
                return ResourceManager.GetString("ErrorNoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating main window:\n{0}\n\n{1} ähnelt.
        /// </summary>
        internal static string ErrorMainWindowCreation {
            get {
                return ResourceManager.GetString("ErrorMainWindowCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error displaying game selection dialog:\n{0} ähnelt.
        /// </summary>
        internal static string ErrorGameSelectionDialog {
            get {
                return ResourceManager.GetString("ErrorGameSelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the maximum number of backups to keep: ähnelt.
        /// </summary>
        internal static string PromptSetMaxBackups {
            get {
                return ResourceManager.GetString("PromptSetMaxBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Max Backups ähnelt.
        /// </summary>
        internal static string TitleSetMaxBackups {
            get {
                return ResourceManager.GetString("TitleSetMaxBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Kingdom Come Deliverance 2 Executable ähnelt.
        /// </summary>
        internal static string PromptSelectGameExecutable {
            get {
                return ResourceManager.GetString("PromptSelectGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Game Executable ähnelt.
        /// </summary>
        internal static string TitleSelectGameExecutable {
            get {
                return ResourceManager.GetString("TitleSelectGameExecutable", resourceCulture);
            }
        }
    }
}

