//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCD2_mod_manager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder erstellen Sie Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCD2_mod_manager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KCD2 Mod Manager ähnelt.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in to Nexus Mods ähnelt.
        /// </summary>
        internal static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out of Nexus Mods ähnelt.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Game ähnelt.
        /// </summary>
        internal static string ButtonStartGame {
            get {
                return ResourceManager.GetString("ButtonStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Mod ähnelt.
        /// </summary>
        internal static string ButtonAddMod {
            get {
                return ResourceManager.GetString("ButtonAddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort: Load Order ähnelt.
        /// </summary>
        internal static string ButtonSortLoadOrder {
            get {
                return ResourceManager.GetString("ButtonSortLoadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort: Title ähnelt.
        /// </summary>
        internal static string ButtonSortTitle {
            get {
                return ResourceManager.GetString("ButtonSortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort: Disabled ähnelt.
        /// </summary>
        internal static string ButtonSortDisabled {
            get {
                return ResourceManager.GetString("ButtonSortDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload Mods ähnelt.
        /// </summary>
        internal static string ButtonReloadMods {
            get {
                return ResourceManager.GetString("ButtonReloadMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: Ready ähnelt.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting game with mods... ähnelt.
        /// </summary>
        internal static string StatusStartingGame {
            get {
                return ResourceManager.GetString("StatusStartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game started. ähnelt.
        /// </summary>
        internal static string StatusGameStarted {
            get {
                return ResourceManager.GetString("StatusGameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to start game. ähnelt.
        /// </summary>
        internal static string StatusFailedToStartGame {
            get {
                return ResourceManager.GetString("StatusFailedToStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mods enabled: {0} ähnelt.
        /// </summary>
        internal static string ModsEnabled {
            get {
                return ResourceManager.GetString("ModsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conflicts detected: {0} ähnelt.
        /// </summary>
        internal static string ConflictsDetected {
            get {
                return ResourceManager.GetString("ConflictsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search mods... ähnelt.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Search ähnelt.
        /// </summary>
        internal static string ToolTipClearSearch {
            get {
                return ResourceManager.GetString("ToolTipClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Available ähnelt.
        /// </summary>
        internal static string ToolTipUpdateAvailable {
            get {
                return ResourceManager.GetString("ToolTipUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
        /// </summary>
        internal static string ToolTipMoveUp {
            get {
                return ResourceManager.GetString("ToolTipMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
        /// </summary>
        internal static string ToolTipMoveDown {
            get {
                return ResourceManager.GetString("ToolTipMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Mod ähnelt.
        /// </summary>
        internal static string ToolTipDeleteMod {
            get {
                return ResourceManager.GetString("ToolTipDeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Folder ähnelt.
        /// </summary>
        internal static string ToolTipOpenFolder {
            get {
                return ResourceManager.GetString("ToolTipOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More options ähnelt.
        /// </summary>
        internal static string ToolTipMoreOptions {
            get {
                return ResourceManager.GetString("ToolTipMoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit website ähnelt.
        /// </summary>
        internal static string ContextMenuVisitWebsite {
            get {
                return ResourceManager.GetString("ContextMenuVisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change mod name ähnelt.
        /// </summary>
        internal static string ContextMenuChangeModName {
            get {
                return ResourceManager.GetString("ContextMenuChangeModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change note ähnelt.
        /// </summary>
        internal static string ContextMenuChangeNote {
            get {
                return ResourceManager.GetString("ContextMenuChangeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endorse mod ähnelt.
        /// </summary>
        internal static string ContextMenuEndorseMod {
            get {
                return ResourceManager.GetString("ContextMenuEndorseMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change mod number ähnelt.
        /// </summary>
        internal static string ContextMenuChangeModNumber {
            get {
                return ResourceManager.GetString("ContextMenuChangeModNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle update check ähnelt.
        /// </summary>
        internal static string ContextMenuToggleUpdateCheck {
            get {
                return ResourceManager.GetString("ContextMenuToggleUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Settings ähnelt.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Game Path: ähnelt.
        /// </summary>
        internal static string SetGamePath {
            get {
                return ResourceManager.GetString("SetGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set ähnelt.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Delete Confirmation: ähnelt.
        /// </summary>
        internal static string EnableDeleteConfirmation {
            get {
                return ResourceManager.GetString("EnableDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Dark Mode: ähnelt.
        /// </summary>
        internal static string ToggleDarkMode {
            get {
                return ResourceManager.GetString("ToggleDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Devmode: ähnelt.
        /// </summary>
        internal static string ToggleDevMode {
            get {
                return ResourceManager.GetString("ToggleDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Update Notifications: ähnelt.
        /// </summary>
        internal static string ToggleUpdateNotifications {
            get {
                return ResourceManager.GetString("ToggleUpdateNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Mod Order Creation: ähnelt.
        /// </summary>
        internal static string ToggleModOrderCreation {
            get {
                return ResourceManager.GetString("ToggleModOrderCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language Settings ähnelt.
        /// </summary>
        internal static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Settings ähnelt.
        /// </summary>
        internal static string BackupSettings {
            get {
                return ResourceManager.GetString("BackupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Backup Creation: ähnelt.
        /// </summary>
        internal static string ToggleBackupCreation {
            get {
                return ResourceManager.GetString("ToggleBackupCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup on Startup: ähnelt.
        /// </summary>
        internal static string BackupOnStartup {
            get {
                return ResourceManager.GetString("BackupOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Max Backups: ähnelt.
        /// </summary>
        internal static string SetMaxBackups {
            get {
                return ResourceManager.GetString("SetMaxBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask before deleting mods: ähnelt.
        /// </summary>
        internal static string ToggleDeleteConfirmation {
            get {
                return ResourceManager.GetString("ToggleDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Language: ähnelt.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
    }
}

